In [20]:
import numpy as np
a = list(range(10))
dummy = np.stack((a,a,a,a,a,a,a,a,a,a),axis=1)

In [21]:
dummy

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [22]:
dummy1 = dummy.T

In [23]:
dummy1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
dummy1[dummy1==5]=8

In [25]:
dummy1

array([[0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9]])

# 

In [26]:
R = dummy1
nms_size = 3

In [27]:
for i in range(R.shape[0]-nms_size):
        for j in range(R.shape[1]-nms_size):
            dummy = R[i:i+nms_size,j:j+nms_size]
            dummy[dummy != np.max(dummy)] = 0

In [28]:
R

array([[0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 0, 0, 0, 0, 8, 0, 0, 8, 9],
       [0, 1, 2, 3, 4, 8, 6, 7, 8, 9]])